services:
  - type: web
    name: expense-tracker
    env: docker
    plan: free
    branch: main
    numInstances: 1
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
